### ISSUE TITLE
ダークモードへの対応

### ISSUE THREAD

**Issue by krisfail** [tsukumijima/TwitterRevertRT#1]
#000000(ブラック)や#14202b(ダークブルー)にも対応して欲しい

**Comment by tsukumijima** [comment]
ダークモードのことでしょうか？失念していました…
できるだけ早く対応します。

**Comment by tsukumijima** [comment]
Commit 6e3fde9d0e540fd6c6bada59f898f0defe11aec7 にて対応しました！
という訳で閉じさせていただきます。Chrome ウェブストアへの反映は審査の関係で半日～1日ほど掛かる予定です。しばらくお待ちいただければと思います。

**Comment by tsukumijima** [comment]
Chrome ウェブストアに反映されました！
